### PR TITLE
add(signatureOrder): multiple signatories

### PR DESCRIPTION
**Pull request by mickhansen**

### CODE REVIEW

**Comment by sgryt** [comment]
I’m AFK, will test a bit later on tonight

**Comment by mickhansen** [comment]
No rush. also AFK from now on

**Comment by sgryt** [comment]
image

Rotating the secret makes no difference.

**Comment by mickhansen** [comment]
@sgryt Hmm you somehow ended up in the production deploy preview? Not quite sure how. The link in github links to test for me

**Comment by sgryt** [comment]
> @sgryt Hmm you somehow ended up in the production deploy preview? Not quite sure how. The link in github links to test for me

PEBKAC.

I have tested with 2 signatories, blocking happens when expected, and the block is removed automatically when the active signatory has signed (after a few seconds).

**Pull request merged**
